application: crxdoc-zh
version: 0-2-6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
  expiration: 30d
- url: /favicon\.ico
  static_files: chrome-32.ico
  upload: chrome-32.ico
  expiration: 30d
- url: /google4ee2ea4bf10dbdf8\.html
  static_files: google4ee2ea4bf10dbdf8.html
  upload: google4ee2ea4bf10dbdf8.html
  expiration: 30d
- url: /BingSiteAuth\.xml
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth.xml
  expiration: 30d
#- url: /appcache\.manifest
#  static_files: appcache.manifest
#  upload: appcache.manifest
#  mime_type: text/cache-manifest
- url: /.*
  script: handler.app
  secure: always

env_variables:
  CRXDOCZH_MASTER_API_KEY: '<REPLACE_WITH_YOUR_MASTER_API_KEY>'
  CRXDOCZH_SLAVE_DOCS_APP_DOMAIN: '<REPLACE_WITH_YOUR_DOCS_APP_ID>.appspot.com'
  CRXDOCZH_SLAVE_DOCS_API_KEY: '<REPLACE_WITH_YOUR_DOCS_API_KEY>'
